//require("./set-helpers_test");
require("./service-worker-cache_test");
require("./localstorage-cache_test");
require("./fall-through-cache_test")
require("./combine-requests_test");
require("./cache-requests_test");
require("./persist_test");
require("./constructor_test");
require("./instance-store_test");
require("./parse-data_test");
require("./model_test");
